name: Tests

on:
  pull_request:
  push:
    branches:
      - $default

jobs:
  lint:
    name: Run tests
    runs-on: ubuntu-latest
    container: 'node:14-alpine'
    steps:
    - uses: actions/checkout@v1
    - name: npm ci
      run: npm ci
    - name: npm test
      run: npm test